# Generated by Django 4.2.21 on 2025-06-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0212_rename_credit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'permissions': (('see_private_solution', 'See hidden solutions'), ('see_solution_proposal', 'See solution proposals')), 'verbose_name': 'solution', 'verbose_name_plural': 'solutions'},
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='judge.problem', verbose_name='associated problem'),
        ),
    ]
