# Generated by Django 4.2.21 on 2025-06-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0213_editorial_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='publish_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish date'),
        ),
    ]
