# Generated by Django 4.2.21 on 2025-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_alter_contest_authors_alter_contest_curators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='is_public',
        ),
        migrations.AddField(
            model_name='solution',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='official editorial'),
        ),
    ]
