# Generated by Django 4.2.26 on 2025-12-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_add_magazine_permission'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', '-id'], name='judge_submi_problem_801afc_idx'),
        ),
    ]
