# Generated by Django 4.2.21 on 2025-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_remove_solution_is_public_solution_is_official_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='public visibility'),
        ),
    ]
