# Generated by Django 4.2.26 on 2025-12-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0216_remove_problem_organizations_problem_organization_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', '-id'], name='judge_submi_problem_801afc_idx'),
        ),
    ]
