# Generated by Django 4.2.21 on 2025-06-01 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0216_solution_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='publish_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 12, 5, 42, 744090, tzinfo=datetime.timezone.utc), verbose_name='publish date'),
            preserve_default=False,
        ),
    ]
